language: python

before_script:
- pip2 install --force-reinstall 'ansible===1.9.4'
- pip install 'tox!=2.4.0,>=2.3'

script: tox

notifications:
    email: false

matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8
    - python: 2.7
      env: TOXENV=ansible-lint

sudo: false
