---
## TODO(odyssey4me):
## Whenever the first Rocky tag is issued, this must
## be enabled and modified to include that tag.
#earliest_version: r18.0.0
release_tag_re: '^r\d+\.\d+\.\d+(rc\d+)?'
pre_release_tag_re: '(?P<pre_release>rc\d+$)'
